tpco_cargaEmpresas_Sura/Models/FileManager.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace tpco_cargaEmpresas_Sura.Models
{
    public class FileManager
    {
        [Required]
        public HttpPostedFileBase LoadFile { get; set; }
    }
}

tpco_cargaEmpresas_Sura/Models/ResponseService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace tpco_cargaEmpresas_Sura.Models
{
    public class ResponseService
    {
        public string message { get; set; }
        public string code { get; set; }
    }
}

tpco_cargaEmpresas_Sura/Controllers/AdmonEmpresasController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tpco_cargaEmpresas_Sura.Models;
using tpco_cargaEmpresas_Sura.Utils;

namespace tpco_cargaEmpresas_Sura.Controllers
{
    public class AdmonEmpresasController : Controller
    {
        // GET: AdmonEmpresas
        public ActionResult Index()
        {
            return View();
        }
        

        // GET: AdmonEmpresas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }


        [HttpPost]
        public JsonResult LoadFile(FileManager fileManager)
        {            
           return Json(ClsUtils.ReadFile(fileManager), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public ActionResult DownloadStructure()
        {
            ClsUtils utils = new ClsUtils();
            DataTable dtEmpresas = new DataTable("Empresas");
            dtEmpresas.Columns.Add("NIT", typeof(String));
            dtEmpresas.Columns.Add("Nombre", typeof(String));
            dtEmpresas.Columns.Add("Tipo Empresa", typeof(String));
            dtEmpresas.Columns.Add("Profesional", typeof(String));
            dtEmpresas.Columns.Add("Email", typeof(String));          


            FileContentResult robj;
            //create a new ExcelPackage
            using (ExcelPackage excelPackage = new ExcelPackage())
            {
                //create a WorkSheet
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("Sheet 1");

                //add all the content from the DataTable, starting at cell A1
                worksheet.Cells["A1"].LoadFromDataTable(dtEmpresas, true);


                for (int row = 1; row <= worksheet.Dimension.End.Row; row++)
                {
                    var re = worksheet.Cells[row, 4].Value.ToString();
                    int value;
                    if (int.TryParse(worksheet.Cells[row, 4].Value.ToString().Split('%')[0], out value))
                    {
                        if (value <= 80 && value >= 70)
                        {
                            worksheet.Cells[row, 4].Style.Fill.PatternType = ExcelFillStyle.Solid;
                        }
                        else if (value < 70)
                        {
                            worksheet.Cells[row, 4].Style.Fill.PatternType = ExcelFillStyle.Solid;
                        }

                    }

                }
                using (MemoryStream stream = new MemoryStream())
                {
                    excelPackage.SaveAs(stream);
                    var bytesdata = File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "myFileName.xlsx");
                    robj = bytesdata;
                }

            }

            return Json(robj, JsonRequestBehavior.AllowGet);

        }


        // GET: AdmonEmpresas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdmonEmpresas/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdmonEmpresas/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdmonEmpresas/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: AdmonEmpresas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdmonEmpresas/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

tpco_cargaEmpresas_Sura/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tpco_cargaEmpresas_Sura.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

tpco_cargaEmpresas_Sura/Views/AdmonEmpresas/Index.cshtml
@model tpco_cargaEmpresas_Sura.ViewModel.ViewModelEmpresas
@{
    ViewBag.Title = "Index";
}


<div id="divMain">
    <img src="~/Images/ArlImagen.png" />
    <div id="headerTable">
        <br />
        <div id="headerTableLeft">CARGA EMPRESAS SST</div>
    </div>
    <br />

</div>
<div id="divMain2">

    <div class="input-group">
        
       <br />
        
        <div class="custom-file">
            <input type="file" class="custom-file-input-form" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01" onchange="changeFilename(this)" name="LoadFile" accept=".xlsx, .XLSX" title="Elige un archivo para subir" required>
            <label id="lblfileName" class="custom-file-label" for="inputGroupFile01">Seleccione el archivo...</label>
        </div>
        <br />
        <p class="msj-validation"></p>
        <div class="col-md-12 text-center">
            <button type="button" id="btnload" class="buttonsApp" onclick="Load()">Cargar</button>            
            <button type="button" id="btndownloadstructure" class="buttonsApp" onclick="downloadStructure()">Estructura</button>
        </div>
    </div>      
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>


        function Load() {
            var xhr = new XMLHttpRequest();
            var formdata = buildRequest();
            console.log("va");
            console.log(formdata);

             xhr.open('POST', '@Url.Action("LoadFile", "AdmonEmpresas")');
                xhr.onload = function (oEvent) {
                var json = JSON.parse(oEvent.srcElement.response);
                if (json.code=="-1") {
                    swal({ title: 'Error', text: json.message, timer: 7500, type: 'error', showConfirmButton: true });
                } else {
                    swal({ title: 'Exito', text: json.message, timer: 7500, type: 'success', showConfirmButton: true });
                }
                resetForm();
                };
                xhr.send(formdata);
        }


        function changeFilename(field) {
            if (field.value !== "") {
                document.getElementById('lblfileName').innerHTML = field.value.split('\\').pop();

                var extension = field.files[0].name.split('.').pop();

                if (extension.toLowerCase() !== "xlsx") {
                    $('.msj-validation').css('display', 'block');
                    $('.msj-validation').html("<font color='red'>El archivo debe ser de extensión xlsx</font>");
                    document.forms.form.reset();
                    document.getElementById('lblfileName').innerHTML = 'Elija el archivo...';
                    $("#inputGroupFile01").attr("title", "Elige un archivo para subir");
                } else {
                    if (field.files[0].size == 0) {
                        $('.msj-validation').css('display', 'block');
                        $('.msj-validation').html("<font color='red'>El archivo esta vacio</font>");
                        document.forms.form.reset();
                        document.getElementById('lblfileName').innerHTML = 'Elija el archivo...';
                        $("#inputGroupFile01").attr("title", "Elige un archivo para subir");
                    } else {
                        $('.msj-validation').css('display', 'none');
                        $("#inputGroupFile01").attr("title", field.value.split('\\').pop());
                    }
                }
            } else {
                reset();
                $("#inputGroupFile01").attr("title", "Elige un archivo para subir");
            }
        }

        function downloadStructure()
        {
            jsShowWindowLoad("Por avor espere...");
            event.preventDefault();
             $.ajax({
                type: "POST",
                url: '@Url.Action("DownloadStructure", "AdmonEmpresas")',
                 success: function (res) {
                     $('.loader').addClass('d-none');
                     jsRemoveWindowLoad();
                     var bytes = new Uint8Array(res.FileContents);
                     var blob = new Blob([bytes], { tipo: "application / vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
                     var link = document.createElement("a");
                     link.href = window.URL.createObjectURL(blob);
                     link.download = "EstructuraEmpresas.xlsx";
                     link.click();
                 }
            })

        }

        function jsRemoveWindowLoad() {

            $("#WindowLoad").remove();

        }


        function jsShowWindowLoad(mensaje) {
            jsRemoveWindowLoad();

            if (mensaje === undefined) mensaje = "Procesando la información&amp;lt;br&amp;gt;Espere por favor";

            height = 20;
            var ancho = 0;
            var alto = 0;

            if (window.innerWidth == undefined) ancho = window.screen.width;
            else ancho = window.innerWidth;
            if (window.innerHeight == undefined) alto = window.screen.height;
            else alto = window.innerHeight;

            var heightdivsito = alto / 2 - parseInt(height) / 2;

            imgCentro = "<div style='text-align:center;height:" + alto + "px;'><div  style='color:#000;margin-top:" + heightdivsito + "px; font-size:20px;font-weight:bold'> <div class='loader justify - content - center mt - 3' style='position: absolute; top: 200px; left: 0; right: 20px; width: 20px; height: 20px'></div><label for='exampleInputEmail1' class='text - primary' style='font - size: 20px; font - family: Calibri Light'> Por favor espere .... </label></div></div>";

            div = document.createElement("div");
            div.id = "WindowLoad"
            div.style.width = ancho + "px";
            div.style.height = alto + "px";
            $("body").append(div);

            input = document.createElement("input");
            input.id = "focusInput";
            input.type = "text"

            $("#WindowLoad").append(input);

            $("#focusInput").focus();
            $("#focusInput").hide();

            $("#WindowLoad").html(imgCentro);

        }


    </script>
    <script type="text/javascript" src="~/Scripts/filemanager.js"></script>
    <script src="https://cdn.jsdelivr.net/g/filesaver.js"></script>
}

tpco_cargaEmpresas_Sura/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

tpco_cargaEmpresas_Sura/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

tpco_cargaEmpresas_Sura/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

tpco_cargaEmpresas_Sura/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    <link rel="stylesheet" href="~/Content/Style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/style.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="../libs/sweetalert2-7.0.5/sweetalert2.js"></script>
    <link href="../libs/sweetalert2-7.0.5/sweetalert2.css" rel="stylesheet" />
    <link href="../libs/toastr-2.1.3/build/toastr.css" rel="stylesheet" />
    <script src="../libs/toastr-2.1.3/toastr.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>